# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 347ad7d51138d740bfa3409936c387a43f936142bea8c14ff75b9cf00bc823c47d180e7776f8ee45c9dbec3443e6449677da568a9eae4a8b6c951983ce42d005

test:
  secret_key_base: 29688b4dc8ab5b81521c3b95139f59ab5fc57aa2ee13c6234dcdcea5744875361af9b1c5fe4e6ad301735aaf48e854196d5fb42c79b40fad71a5bdc1d7e79333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
